language: node_js
node_js:
  - "7.10.1"
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - sudo apt-get -qq update
  - sudo apt-cache policy rabbitmq
  - sudo apt-get install -y rabbitmq
install:
  - yarn install
script:
  - npm test